# Generated by Django 4.2.13 on 2024-06-30 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_country_customuser_dob_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Reading', 'Reading'), ('Traveling', 'Traveling'), ('Cooking', 'Cooking'), ('Sports', 'Sports')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.ManyToManyField(related_name='user_hobbies', to='accounts.hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hobbies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
