# Generated by Django 4.2.13 on 2024-06-30 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hobby_userhobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Literature', 'Literature'), ('Travel', 'Travel'), ('Food', 'Food'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Politics', 'Politics'), ('Environment', 'Environment'), ('Sports', 'Sports'), ('History', 'History')], max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Traveling', 'Traveling'), ('Cooking', 'Cooking'), ('Sports', 'Sports'), ('Gardening', 'Gardening'), ('Gaming', 'Gaming'), ('Fitness', 'Fitness'), ('Photography', 'Photography'), ('Writing', 'Writing'), ('Dancing', 'Dancing')], max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest', models.ManyToManyField(related_name='user_interest', to='accounts.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
