# Generated by Django 4.2.13 on 2024-06-30 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_interest_alter_hobby_name_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking_habit', models.BooleanField(default=False)),
                ('drinking_habit', models.BooleanField(default=False)),
                ('Interest', models.ManyToManyField(related_name='user_activities', to='accounts.interest')),
                ('hobbies', models.ManyToManyField(related_name='user_activities', to='accounts.hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='Interest',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserHobby',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
