# Generated by Django 4.2.13 on 2024-06-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
